module.exports = {
    products: [
        {
            _id: '1',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image: '/images/d1.jpg',
            price: 79,
            brand: 'Hiskywin',
             rating: 4.5,
             numReviews: 10,
             countInStock: 6,
        },
        {
            _id: '2',
            name: ' Nike Full-Zip Hoodie Mens Workout Sweatshirt',
            category: 'Shirts',
            image: '/images/d2.jpg',
            price: 80,
            brand: 'Nide ',
             rating: 5,
             numReviews: 51 ,
             countInStock: 10,
        },
        {
            _id: '3',
            name: 'Adidas Mens Long Sleeve Hoodie',
            category: 'Shirts',
            image: '/images/d3.jpg',
            price: 49,
            brand: 'Adidas ',
             rating: 4,
             numReviews: 45,
             ountInStock: 3
        },
        {
            _id: '4',
            name: 'Under Armour Mens Sportstyle Tricot Joggers',
            category: 'Pants',
            image: '/images/p1.jpg',
            price: 90,
            brand: 'Under Armour',
             rating: 2.5,
             numReviews: 198 ,
             countInStock: 6,
        },
        {
            _id: '5',
            name: 'Champion Mens Graphic Powerblend Fleece Jogger',
            category: 'Pants',
            image: '/images/p2.jpg',
            price: 99,
            brand: 'Champion ',
             rating: 3.5,
             numReviews: 89 ,
             countInStock: 6,
        },
        {
            _id: '6',
            name: ' Aelfric Aden Joggers Pants Long Multi-Pockets',
            category: 'Pants',
            image: '/images/p3.jpg',
            price: 85,
            brand: 'Aelfric Eden ',
             rating: 4.5,
             numReviews: 45 ,
             countInStock: 6,
        },
    ],
};